package BiddingSystem;

import BiddingSystem.Player;
import BiddingSystem.BiddingData.Actions.ContractBid;
import BiddingSystem.BiddingData.Actions.PassAction;
import BiddingSystem.BiddingData.Actions.PlayerAction;
import BiddingSystem.BiddingLogic.BiddingManager;
import logic.Deck;
import logic.PlayerPosition;
import logic.Strain;
import logic.Suit; // ADJUST: use your actual Suit enum's package/values

import static java.lang.IO.println;

//GENERATED BY AI FOR TESTING PURPOSES!!!
/**
 * Manual driver for testing the bidding system in isolation, no UI needed.
 * This is NOT a unit test framework (JUnit) — just a runnable trace so you
 * can eyeball whether the sequence of accept/reject decisions matches what
 * you'd expect from real bridge rules.
 *
 * ASSUMPTIONS you'll need to fix to compile:
 *  - Player(String name, Deck d, int pos) requires a Deck — passing null here
 *    since bidding logic shouldn't care about hand contents. If Player's
 *    constructor or getters break on a null Deck, you may need a dummy Deck.
 *  - Suit enum values below (CLUBS, DIAMONDS, HEARTS, SPADES) are guesses —
 *    replace with whatever your actual Suit enum defines.
 *  - Assumes BiddingManager currently has a void ActionPlayed(PlayerAction).
 *    Once you implement Option A (boolean return + validation), update the
 *    calls below to check the returned boolean instead of assuming success.
 */
public class TestRun {

    public static void main(String[] args) {
        // Seats: 0=North, 1=East, 2=South, 3=West
        Player north = new Player("North", null, PlayerPosition.NORTH);
        Player east  = new Player("East",  null, PlayerPosition.EAST);
        Player south = new Player("South", null, PlayerPosition.SOUTH);
        Player west  = new Player("West", null, PlayerPosition.WEST);
        Player[] players = { south, west, east, north };

        // Dealer = North (seat 0) for this test
        Deck deck = new Deck();
        deck.shuffle();
        DealCards.dealHands(deck, players);
        //will print player hands
        BiddingManager manager = new BiddingManager(PlayerPosition.SOUTH, players);
        for (manager.getPl

        System.out.println("=== Test 1: basic legal escalation ===");
        playAndReport(manager, new PassAction());                    // North passes
        playAndReport(manager, new ContractBid(1, Strain.CLUBS));      // East bids 1C
        playAndReport(manager, new PassAction());                    // South passes
        playAndReport(manager, new ContractBid(2, Strain.HEARTS));     // West bids 2H (should be legal, higher level)

        System.out.println();
        System.out.println("=== Test 2: illegal lower bid (should be rejected once validation is wired in) ===");
        // NOTE: until you wire validateBid into ActionPlayed, this will currently
        // just get logged with no rejection — that's the gap you're about to close.
        playAndReport(manager, new ContractBid(1, Strain.SPADES));     // North tries 1S after 2H — illegal, lower level

        System.out.println();
        System.out.println("=== Test 3: same-level, lower-suit bid (should be rejected) ===");
        playAndReport(manager, new ContractBid(2, Strain.CLUBS));      // 2C after 2H — same level, lower suit, illegal

        System.out.println();
        System.out.println("=== Test 4: same-level, higher-suit bid (should be legal) ===");
        playAndReport(manager, new ContractBid(2, Strain.SPADES));     // 2S after 2H — same level, higher suit, legal

        // Add more sequences here as you build out auction-end detection,
        System.out.println();
        System.out.println("=== Test 5: testing if no trump bids can be made, higher-suit bid (should be legal) ===");
        playAndReport(manager, new ContractBid(2, Strain.NO_TRUMP));

        System.out.println();
        System.out.println("=== Test 5: testing if no trump comparisons are correct, next player bids the same thing (should be rejected) ===");
        playAndReport(manager, new ContractBid(2, Strain.NO_TRUMP));
        // e.g. three consecutive passes after a bid, or four passes with no bid.
    }

    /**
     * Plays an action and prints out the state so you can eyeball correctness.
     * Update this once ActionPlayed returns a boolean (Option A) so it reports
     * accepted/rejected explicitly instead of just "played".
     */
    private static void playAndReport(BiddingManager manager, PlayerAction action) {
        Player actingPlayer = manager.getCurrentPlayer();
        System.out.println(actingPlayer.getUsername() + " attempts: " + action.getDisplayString());

        boolean accepted = manager.ActionPlayed(action);
         System.out.println("  -> " + (accepted ? "ACCEPTED" : "REJECTED"));
        System.out.println("  Next to act: " + manager.getCurrentPlayer().getUsername());
    }
}
